app = "vf-chat"
primary_region = "otp"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[checks.app]
  grace_period = "10s"
  interval = "15s"
  port = 8080
  timeout = "2s"
  type = "tcp"
